title: JustDeploy.tech
description: Docs for deploying your website effortlessly in minutes and not hours.
theme: just-the-docs
color_scheme: dark

url: https://justdeploytech.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Variables across the site
domain: justdeploy.tech
